// <auto-generated />
using HuiLianMedical.WebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HuiLianMedical.WebApi.Migrations
{
    [DbContext(typeof(MedicalContext))]
    [Migration("20240805053958_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("CategoryModelCommodityModel", b =>
                {
                    b.Property<string>("CategoryKey")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("CommoditiesKey")
                        .HasColumnType("varchar(32)");

                    b.HasKey("CategoryKey", "CommoditiesKey");

                    b.HasIndex("CommoditiesKey");

                    b.ToTable("CategoryModelCommodityModel");
                });

            modelBuilder.Entity("HuiLianMedical.WebApi.Models.AidModel", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.HasKey("Key");

                    b.ToTable("AidModel");
                });

            modelBuilder.Entity("HuiLianMedical.WebApi.Models.CategoryModel", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.HasKey("Key");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("HuiLianMedical.WebApi.Models.CommodityModel", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("CreateTime")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stock")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("UserModelId")
                        .HasColumnType("varchar(32)");

                    b.HasKey("Key");

                    b.HasIndex("UserModelId");

                    b.ToTable("Commodities");
                });

            modelBuilder.Entity("HuiLianMedical.WebApi.Models.UserModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Avatar")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Identity")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CategoryModelCommodityModel", b =>
                {
                    b.HasOne("HuiLianMedical.WebApi.Models.CategoryModel", null)
                        .WithMany()
                        .HasForeignKey("CategoryKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HuiLianMedical.WebApi.Models.CommodityModel", null)
                        .WithMany()
                        .HasForeignKey("CommoditiesKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HuiLianMedical.WebApi.Models.CommodityModel", b =>
                {
                    b.HasOne("HuiLianMedical.WebApi.Models.UserModel", null)
                        .WithMany("Commodities")
                        .HasForeignKey("UserModelId");
                });

            modelBuilder.Entity("HuiLianMedical.WebApi.Models.UserModel", b =>
                {
                    b.Navigation("Commodities");
                });
#pragma warning restore 612, 618
        }
    }
}
